# Generated by Django 4.2.2 on 2023-12-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog')], default='Blog', max_length=10),
        ),
    ]
