# Generated by Django 4.2.2 on 2023-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_storycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycategory',
            name='CatStory',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'In the News'), ('wins', 'Wins Wall')], default='blog', max_length=20),
        ),
    ]
