# Generated by Django 4.2.2 on 2023-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_storycategory_catstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'In the News'), ('case', 'Case Studies')], default='blog', max_length=10),
        ),
        migrations.AlterField(
            model_name='storycategory',
            name='CatStory',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'In the News'), ('case', 'Case Studies')], default='blog', max_length=20),
        ),
    ]
