# Generated by Django 4.2.2 on 2023-12-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
